/* ─────────────────────────────────────────────────────────────
   JPE Studio — Documentation Generator (Phase 22)
   Auto-generates mod documentation from XML tuning comments
   and STBL strings. Output formats: Markdown, HTML, JSON.
   Live preview pane, section toggles, and export/copy.
   ───────────────────────────────────────────────────────────── */
import { useState, useMemo } from "react";
import {
  X, FileText, FileCode, Braces, Download, Copy, Check,
  RefreshCw, Eye, Settings2, ChevronDown, ChevronRight,
  BookOpen, Hash, Globe, Star, Briefcase, Zap,
} from "lucide-react";
import { motion, AnimatePresence } from "./jpe-motion";
import { T } from "../pages/jpe-theme";
import { toast } from "sonner";

/* ── Types ── */
type OutputFormat = "markdown" | "html" | "json";

interface DocSection {
  id: string;
  label: string;
  included: boolean;
  icon: typeof Star;
}

/* ── Section config ── */
const SECTIONS: DocSection[] = [
  { id:"overview",      label:"Overview",            included:true,  icon:BookOpen },
  { id:"trait-details", label:"Trait Properties",    included:true,  icon:Star    },
  { id:"buffs",         label:"Buffs & Moodlets",    included:true,  icon:Zap     },
  { id:"interactions",  label:"Interactions",        included:true,  icon:Hash    },
  { id:"locales",       label:"Locale Coverage",     included:true,  icon:Globe   },
  { id:"dependencies",  label:"Dependencies",        included:false, icon:Briefcase},
  { id:"changelog",     label:"Version History",     included:false, icon:FileText},
];

/* ── Markdown template ── */
const makeMd = (secs: DocSection[]) => {
  const inc = new Set(secs.filter(s=>s.included).map(s=>s.id));
  return [
    `# Evil Trait Override — Documentation\n\n> Generated by JPE Studio v4.2.0 on ${new Date().toLocaleDateString()}\n`,
    inc.has("overview") ? `## Overview\n\nAdds the **Evil** CAS trait to The Sims 4, granting a set of unique social interactions, persistent buffs, and career bonuses.\n\n| Field         | Value                    |\n|---------------|-------------------------|\n| Package ID    | \`com.author.eviltrait\`   |\n| Version       | 1.5.0                    |\n| Game Version  | 1.107.x                  |\n| Author        | ModAuthor                |\n` : "",
    inc.has("trait-details") ? `## Trait Properties\n\n\`\`\`xml\n<TunableSimData n="trait_Evil" s="0x001B3FC2">\n  <Tunable n="trait_type" t="TraitType" ev="PERSONALITY"/>\n  <Tunable n="conflict_weight" ev="20"/>\n  <Tunable n="whim_weight" ev="50"/>\n</TunableSimData>\n\`\`\`\n\n**Conflict Weight:** 20 — This trait conflicts moderately with Good, Cheerful, and Goofball.\n` : "",
    inc.has("buffs") ? `## Buffs & Moodlets\n\n| Buff               | Mood     | Weight | Duration |\n|--------------------|----------|--------|----------|\n| \`buff_EvilGlee\`    | Playful  | 3      | 4 hours  |\n| \`buff_MeanSpirit\`  | Angry    | 2      | 2 hours  |\n` : "",
    inc.has("interactions") ? `## Interactions\n\n- **Be Evil** — Mean · Autonomous · requires Evil trait\n- **Scheme in Secret** — Mischief · Solo · requires Mischief ≥ 3\n- **Intimidate** — Mean · Requires target Sim in same room\n` : "",
    inc.has("locales") ? `## Locale Coverage\n\n| Locale | Status    | Completion |\n|--------|-----------|------------|\n| en-US  | ✅ Full   | 100%       |\n| es-ES  | ✅ Full   | 98%        |\n| fr-FR  | ⚠️ Partial | 82%       |\n| de-DE  | ⚠️ Partial | 77%       |\n| pt-BR  | ❌ Missing | 0%        |\n` : "",
    inc.has("dependencies") ? `## Dependencies\n\n- **EP01** — Get to Work (career system)\n- **GP09** — Paranormal Stuff (lot haunting)\n` : "",
    inc.has("changelog") ? `## Version History\n\n### v1.5.0 (2026-03-11)\n- Added Translation Memory with TMX export\n- Mod Validator: 15 validation rules\n\n### v1.4.0 (2026-02-28)\n- Localization Coverage analytics\n- Workspace Profiles snapshot system\n` : "",
  ].filter(Boolean).join("\n");
};

const makeHtml = (secs: DocSection[]) => {
  const md = makeMd(secs);
  return `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8"/>\n  <title>Evil Trait — Mod Docs</title>\n  <style>body{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;color:#e2e8f0;background:#0a0c10;padding:0 24px}h1{color:#A78BFA}h2{color:#63B3ED;border-bottom:1px solid #1a1f2e;padding-bottom:8px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #1a1f2e}code{background:#0f1116;padding:2px 6px;border-radius:4px;color:#90CDF4}pre{background:#0f1116;padding:16px;border-radius:8px;overflow-x:auto}</style>\n</head>\n<body>\n<!-- Auto-generated from Markdown -->\n<pre>${md.replace(/</g,"&lt;")}</pre>\n</body>\n</html>`;
};

const makeJson = (secs: DocSection[]) => {
  const inc = new Set(secs.filter(s=>s.included).map(s=>s.id));
  return JSON.stringify({
    meta: { name:"Evil Trait Override", version:"1.5.0", packageId:"com.author.eviltrait", generatedAt:new Date().toISOString() },
    ...(inc.has("trait-details") ? { traitProperties: { tuningKey:"0x001B3FC2", traitType:"PERSONALITY", conflictWeight:20, whimWeight:50 } } : {}),
    ...(inc.has("buffs") ? { buffs: [{ id:"buff_EvilGlee", mood:"Playful", weight:3, durationHrs:4 }, { id:"buff_MeanSpirit", mood:"Angry", weight:2, durationHrs:2 }] } : {}),
    ...(inc.has("interactions") ? { interactions: [{ id:"interaction_BeEvil", category:"Mean", autonomous:true }, { id:"interaction_Scheme", category:"Mischief", skillReq:"Mischief 3" }] } : {}),
    ...(inc.has("locales") ? { locales: { "en-US":"100%", "es-ES":"98%", "fr-FR":"82%", "de-DE":"77%", "pt-BR":"0%" } } : {}),
  }, null, 2);
};

export function DocGenerator({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [format, setFormat]     = useState<OutputFormat>("markdown");
  const [sections, setSections] = useState<DocSection[]>(SECTIONS);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied]     = useState(false);

  const output = useMemo(() => {
    if (format === "markdown") return makeMd(sections);
    if (format === "html")     return makeHtml(sections);
    return makeJson(sections);
  }, [format, sections]);

  const toggleSection = (id: string) =>
    setSections(prev => prev.map(s => s.id === id ? { ...s, included: !s.included } : s));

  const copyOutput = () => {
    navigator.clipboard.writeText(output).then(() => { setCopied(true); setTimeout(()=>setCopied(false),1500); toast.success("Documentation copied"); });
  };

  const download = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 600));
    setGenerating(false);
    const ext = format === "markdown" ? "md" : format === "html" ? "html" : "json";
    toast.success(`Exported evil-trait-docs.${ext}`, { description: `${output.split("\n").length} lines · ${Math.round(output.length/1024*10)/10} KB` });
  };

  const FORMATS: { id: OutputFormat; label: string; icon: typeof FileText; color: string }[] = [
    { id:"markdown", label:"Markdown",  icon:FileText, color:T.cyan   },
    { id:"html",     label:"HTML",      icon:FileCode, color:T.amber  },
    { id:"json",     label:"JSON",      icon:Braces,   color:T.violet },
  ];

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div className="fixed inset-0 z-[200] flex items-center justify-center"
          initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}
          style={{background:"rgba(0,0,0,0.82)",backdropFilter:"blur(12px)"}}
          onClick={e=>{if(e.target===e.currentTarget)onClose();}}>
          <motion.div initial={{opacity:0,scale:0.97,y:12}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:0.97,y:12}}
            transition={{duration:0.22,ease:[0.16,1,0.3,1]}}
            className="relative flex rounded-2xl overflow-hidden"
            style={{width:"min(980px,97vw)",height:"min(700px,90vh)",background:T.bgElevated,border:`1px solid ${T.border}`,boxShadow:`0 40px 80px rgba(0,0,0,0.7),inset 0 1px 0 rgba(255,255,255,0.04)`}}>

            <div className="absolute top-0 left-0 right-0 h-[2px]" style={{background:`linear-gradient(90deg,transparent 5%,${T.cyan}80,${T.amber}80,transparent 95%)`}}/>

            {/* Config sidebar */}
            <div className="flex flex-col flex-shrink-0 overflow-hidden" style={{width:240,borderRight:`1px solid ${T.border}`,background:T.bgPanel}}>
              <div className="flex items-center justify-between px-4 py-3 flex-shrink-0" style={{borderBottom:`1px solid ${T.border}`}}>
                <div className="flex items-center gap-2">
                  <BookOpen size={14} color={T.cyan}/>
                  <span style={{fontSize:13,fontWeight:700,color:T.textPrimary,fontFamily:T.display}}>Doc Generator</span>
                </div>
                <button onClick={onClose} className="w-6 h-6 rounded-lg flex items-center justify-center hover:bg-white/10"><X size={12} color={T.textMuted}/></button>
              </div>

              {/* Format picker */}
              <div className="p-4 space-y-2 flex-shrink-0" style={{borderBottom:`1px solid ${T.border}`}}>
                <div style={{fontSize:9,fontWeight:700,color:T.textMuted,letterSpacing:"0.06em",marginBottom:6}}>OUTPUT FORMAT</div>
                {FORMATS.map(f=>{
                  const Icon=f.icon; const active=format===f.id;
                  return (
                    <button key={f.id} onClick={()=>setFormat(f.id)}
                      className="w-full flex items-center gap-2 px-3 py-2 rounded-xl transition-all"
                      style={{background:active?`${f.color}10`:"rgba(255,255,255,0.02)",border:`1px solid ${active?f.color:T.borderSubtle}`}}>
                      <Icon size={13} color={active?f.color:T.textMuted}/>
                      <span style={{fontSize:11,fontWeight:active?700:400,color:active?T.textPrimary:T.textMuted}}>{f.label}</span>
                      {active&&<Check size={10} color={f.color} className="ml-auto"/>}
                    </button>
                  );
                })}
              </div>

              {/* Section toggles */}
              <div className="flex-1 overflow-y-auto p-4 space-y-1.5">
                <div style={{fontSize:9,fontWeight:700,color:T.textMuted,letterSpacing:"0.06em",marginBottom:6}}>SECTIONS</div>
                {sections.map(s=>{
                  const Icon=s.icon;
                  return (
                    <button key={s.id} onClick={()=>toggleSection(s.id)}
                      className="w-full flex items-center gap-2 px-3 py-2 rounded-xl transition-all"
                      style={{background:s.included?"rgba(255,255,255,0.02)":"transparent",border:`1px solid ${s.included?T.borderSubtle:"transparent"}`}}>
                      <div className="w-4 h-4 rounded flex items-center justify-center flex-shrink-0 transition-all"
                        style={{background:s.included?T.emerald:"transparent",border:`1px solid ${s.included?T.emerald:T.borderSubtle}`}}>
                        {s.included&&<Check size={9} color="#fff"/>}
                      </div>
                      <Icon size={11} color={s.included?T.textSecondary:T.textMuted}/>
                      <span style={{fontSize:11,color:s.included?T.textSecondary:T.textMuted}}>{s.label}</span>
                    </button>
                  );
                })}
              </div>

              {/* Actions */}
              <div className="p-4 space-y-2 flex-shrink-0" style={{borderTop:`1px solid ${T.borderSubtle}`}}>
                <button onClick={download} disabled={generating}
                  className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl transition-all disabled:opacity-50"
                  style={{fontSize:12,fontWeight:700,color:"#fff",background:`linear-gradient(135deg,${T.cyan}CC,${T.violet}CC)`}}>
                  {generating?<><RefreshCw size={12} className="animate-spin"/>Exporting…</>:<><Download size={12}/>Export</>}
                </button>
                <button onClick={copyOutput}
                  className="w-full flex items-center justify-center gap-2 py-2 rounded-xl transition-all hover:bg-white/5"
                  style={{fontSize:11,color:copied?T.emerald:T.textMuted,border:`1px solid ${T.borderSubtle}`}}>
                  {copied?<><Check size={11}/>Copied!</>:<><Copy size={11}/>Copy</>}
                </button>
              </div>
            </div>

            {/* Preview pane */}
            <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2.5 flex-shrink-0" style={{borderBottom:`1px solid ${T.border}`,background:T.bgSurface}}>
                <div className="flex items-center gap-2">
                  <Eye size={12} color={T.textMuted}/>
                  <span style={{fontSize:9,fontWeight:700,color:T.textMuted,letterSpacing:"0.06em"}}>PREVIEW</span>
                  <span style={{fontSize:9,fontFamily:T.mono,color:T.textDim}}>evil-trait-docs.{format === "markdown" ? "md" : format} · {Math.round(output.length/1024*10)/10} KB · {output.split("\n").length} lines</span>
                </div>
                <span style={{fontSize:9,color:T.textDim}}>{sections.filter(s=>s.included).length}/{sections.length} sections included</span>
              </div>
              <div className="flex-1 overflow-auto p-5">
                <pre style={{fontSize:11,fontFamily:T.mono,color:format==="json"?T.violet:format==="html"?T.amber:T.cyan,lineHeight:1.7,whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{output}</pre>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

export default DocGenerator;
