import { create } from 'zustand';
import {
  Connection,
  Edge,
  EdgeChange,
  Node,
  NodeChange,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges
} from '@xyflow/react';
import { v4 as uuidv4 } from 'uuid';
import dagre from 'dagre';

export type JpeNodeType = 'trigger' | 'action' | 'condition';

export interface JpeNodeData extends Record<string, unknown> {
  label: string;
  type: JpeNodeType;
  value?: string;
  subType?: string;
}

interface VisualState {
  nodes: Node<JpeNodeData>[];
  edges: Edge[];
  onNodesChange: (changes: NodeChange<Node<JpeNodeData>>[]) => void;
  onEdgesChange: (changes: EdgeChange[]) => void;
  onConnect: (connection: Connection) => void;
  setNodes: (nodes: Node<JpeNodeData>[]) => void;
  setEdges: (edges: Edge[]) => void;
  addNode: (type: JpeNodeType, position: { x: number, y: number }, data: Partial<JpeNodeData>) => void;
  generateJpe: () => string;
  autoLayout: (direction?: 'TB' | 'LR') => void;
  parseJpeToNodes: (code: string) => void;
}

export const useVisualStore = create<VisualState>((set, get) => ({
  nodes: [
    {
      id: 'node-start',
      type: 'trigger',
      position: { x: 250, y: 5 },
      data: { label: 'On Sim Spawn', type: 'trigger', subType: 'sims.spawn' },
    }
  ],
  edges: [],
  onNodesChange: (changes) => {
    set({
      nodes: applyNodeChanges(changes, get().nodes),
    });
  },
  onEdgesChange: (changes) => {
    set({
      edges: applyEdgeChanges(changes, get().edges),
    });
  },
  onConnect: (connection) => {
    set({
      edges: addEdge(connection, get().edges),
    });
  },
  setNodes: (nodes) => set({ nodes }),
  setEdges: (edges) => set({ edges }),

  addNode: (type, position, data) => {
    const newNode: Node<JpeNodeData> = {
      id: uuidv4(),
      type,
      position,
      data: {
        label: data.label || 'New Node',
        type,
        ...data,
      },
    };
    set({ nodes: [...get().nodes, newNode] });
  },

  generateJpe: () => {
    const { nodes, edges } = get();
    let jpeCode = "# GENERATED BY JPE VISUAL EDITOR\n\n";

    const triggers = nodes.filter(n => n.data.type === 'trigger');

    const traverse = (nodeId: string, visited: Set<string>, indent: string = ""): string => {
      if (visited.has(nodeId)) return "";
      visited.add(nodeId);

      const node = nodes.find(n => n.id === nodeId);
      if (!node) return "";

      let code = "";
      if (node.data.type === 'action') {
        code += `${indent}${node.data.value || '# assignment'}\n`;
        const nextEdge = edges.find(e => e.source === nodeId);
        if (nextEdge) {
          code += traverse(nextEdge.target, visited, indent);
        }
      } else if (node.data.type === 'condition') {
        code += `${indent}IF ${node.data.value?.replace(/^if\s+/i, '') || 'condition'}\n`;
        const trueEdge = edges.find(e => e.source === nodeId && e.sourceHandle === 'true');
        const falseEdge = edges.find(e => e.source === nodeId && e.sourceHandle === 'false');
        
        if (trueEdge) {
          code += traverse(trueEdge.target, new Set(visited), indent + "  ");
        }
        if (falseEdge) {
          code += `${indent}ELSE\n`;
          code += traverse(falseEdge.target, new Set(visited), indent + "  ");
        }
        code += `${indent}ENDIF\n`;
      }
      return code;
    };

    triggers.forEach(trigger => {
      jpeCode += `[WHEN ${trigger.data.subType || 'unknown'}]\n`;
      const nextEdge = edges.find(e => e.source === trigger.id);
      if (nextEdge) {
        jpeCode += traverse(nextEdge.target, new Set(), "");
      }
      jpeCode += "\n";
    });

    return jpeCode;
  },

  autoLayout: (direction = 'TB') => {
    const { nodes, edges } = get();
    const dagreGraph = new dagre.graphlib.Graph();
    dagreGraph.setDefaultEdgeLabel(() => ({}));

    // Industrial Layout Configuration
    const nodeWidth = 240;
    const nodeHeight = 160;

    dagreGraph.setGraph({ 
      rankdir: direction,
      ranksep: 80,
      nodesep: 50,
      marginx: 100,
      marginy: 100
    });

    nodes.forEach((node) => {
      dagreGraph.setNode(node.id, { width: nodeWidth, height: nodeHeight });
    });

    edges.forEach((edge) => {
      dagreGraph.setEdge(edge.source, edge.target);
    });

    dagre.layout(dagreGraph);

    const layoutedNodes = nodes.map((node) => {
      const nodeWithPosition = dagreGraph.node(node.id);
      return {
        ...node,
        position: {
          x: nodeWithPosition.x - nodeWidth / 2,
          y: nodeWithPosition.y - nodeHeight / 2,
        },
      };
    });

    set({ nodes: layoutedNodes });
  },

  parseJpeToNodes: (code: string) => {
    if (!code || code.trim() === '') return;
    
    const lines = code.split('\n');
    const nodes: Node<JpeNodeData>[] = [];
    const edges: Edge[] = [];
    
    let lastNodeId: string | null = null;
    const ifStack: { id: string, hasElse: boolean }[] = [];

    lines.forEach((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;

      let newNode: Node<JpeNodeData> | null = null;

      // Detect Trigger [WHEN ...]
      const whenMatch = trimmed.match(/^\[WHEN\s+(.+)\]$/i);
      if (whenMatch) {
         newNode = {
           id: `node-${uuidv4()}`,
           type: 'trigger',
           position: { x: 0, y: 0 },
           data: { label: 'Event Trigger', type: 'trigger', subType: whenMatch[1] }
         };
         lastNodeId = newNode.id;
      }

      // Detect IF
      const ifMatch = trimmed.match(/^IF\s+(.+)$/i);
      if (ifMatch) {
         newNode = {
           id: `node-${uuidv4()}`,
           type: 'condition',
           position: { x: 0, y: 0 },
           data: { label: 'Condition', type: 'condition', value: ifMatch[1] }
         };
         if (lastNodeId) {
            edges.push({ id: `e-${uuidv4()}`, source: lastNodeId, target: newNode.id });
         }
         ifStack.push({ id: newNode.id, hasElse: false });
         lastNodeId = newNode.id; // Next node connects to "True" by default? 
         // Actually, xyflow logic needs sourceHandle: 'true'
      }

      // Detect ELSE
      if (trimmed.toUpperCase() === 'ELSE') {
         const currentIf = ifStack[ifStack.length - 1];
         if (currentIf) {
            currentIf.hasElse = true;
            lastNodeId = currentIf.id; // Reset lastNodeId to the IF node to branch out to False
         }
         return;
      }

      // Detect ENDIF
      if (trimmed.toUpperCase() === 'ENDIF') {
         ifStack.pop();
         // Complexity: ENDIF should probably merge back. For now, simple linear.
         return;
      }

      // Detect Action (Regular Line)
      if (!newNode && !trimmed.match(/^(IF|ELSE|ENDIF|\[WHEN)/i)) {
         newNode = {
           id: `node-${uuidv4()}`,
           type: 'action',
           position: { x: 0, y: 0 },
           data: { label: 'Action', type: 'action', value: trimmed }
         };
         
         if (lastNodeId) {
            const currentIf = ifStack[ifStack.length - 1];
            let sourceHandle = undefined;
            
            // If the last node was a condition, we need to decide if this is True or False path
            const lastNode = nodes.find(n => n.id === lastNodeId);
            if (lastNode?.type === 'condition') {
               sourceHandle = currentIf?.hasElse ? 'false' : 'true';
            }

            edges.push({ 
              id: `e-${uuidv4()}`, 
              source: lastNodeId, 
              target: newNode.id,
              sourceHandle
            });
         }
         lastNodeId = newNode.id;
      }

      if (newNode) nodes.push(newNode);
    });

    set({ nodes, edges });
    get().autoLayout('TB');
  },
}));
